config/routes.rb
Rails.application.routes.draw do
  post "/authenticate", to: "home#authenticate"
  post "/rsvp", to: "home#rsvp"
  post "/suggestions", to: "home#suggestions"

  get "/:locale" => "home#index", as: :locale_root

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  helper_method :logged_in?


  def logged_in?
    session[:login]
  end


  private

  def auth password
    if ENV["PASSWORDS"].split(",").include?(password.downcase)
      session[:login] = Digest::MD5.hexdigest(password)
      true
    else
      false
    end
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def authenticate
    auth params[:password]
    if logged_in?
      redirect_to locale_root_path(locale: I18n.locale),
        notice: I18n.t('notices.authenticated')
    else
      redirect_to locale_root_path(locale: I18n.locale),
        alert: I18n.t('notices.authentication_failed')
    end
  end

  def rsvp
    RsvpMailer.rsvp(params[:name], params[:email], params[:notes], params[:answer]).
      deliver_later
    redirect_to locale_root_path(locale: I18n.locale),
      notice: I18n.t('notices.email')
  end

  def suggestions
    RsvpMailer.suggestions(params[:name], params[:email],
                           params[:suggestions]).deliver_later
    redirect_to locale_root_path(locale: I18n.locale),
      notice: I18n.t('notices.email')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact.html.erb
<section id="contact" class="contact-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <h1><%= t("contact.header") %></h1>
        <p class="tagline"><%= t("contact.tagline") %></p>
        <%= form_tag("/rsvp", class: "form-horizontal") do %>
          <%= hidden_field_tag :locale, I18n.locale %>
          <div class="form-group">
            <%= text_field_tag "name", nil, class: "form-control",
              placeholder: t("contact.your_name") %>
          </div>
          <div class="form-group">
            <%= select_tag "answer", options_for_select([t('contact.option_1'),
                                                         t('contact.option_2'),
                                                         t('contact.option_3')]),
            class: "form-control", include_blank: t("contact.answer") %>
          </div>
          <div class="form-group">
            <%= text_field_tag "email", nil, class: "form-control",
              placeholder: t("contact.email") %>
          </div>
          <div class="form-group">
            <%= text_area_tag "notes", nil, class: "form-control",
              placeholder: t("contact.notes") %>
          </div>
          <%= submit_tag t("contact.send"), class: "btn btn-default" %>
        <% end %>
      </div>
      <div class="col-lg-3"></div>
    </div>
  </div>
</section>

app/views/home/_info.html.erb
<section id="info" class="info-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div id="map"></div>
      </div>
    </div>
  </div>
</section>

app/views/home/_intro.html.erb
<section id="intro" class="intro-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= flash_messages %>
        <p class="logo"><%= image_tag('logo/logo.svg') %></p>
        <% if logged_in? %>
          <h1 class="home">Porto</h1>
          <p><%= l(Date.parse('12/11/2016'), format: :long) %></p>
        <% end %>

        <p class="heart">
          <%= render partial: "svgs/heart" %>
        </p>
        <% if logged_in? %>
          <p class="arrow">
            <a class="page-scroll" href="#story">
              <%= render partial: "svgs/arrow" %>
            </a>
          </p>
        <% else %>
          <% placeholder = ["city_lived", "city_met"].shuffle.first %>
          <%= form_tag authenticate_path, class: "form-inline" do %>
            <%= hidden_field_tag :locale, I18n.locale %>
            <div class="form-group">
              <%= label_tag "password", nil, class: "sr-only" %>
              <%= text_field_tag "password", nil, class: "form-control psswd",
                placeholder: t("intro.#{placeholder}") %>
            </div>
            <%= submit_tag t('intro.login_button'),
              class: "btn btn-default"  %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/_list.html.erb
<section id="list" class="list-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
          <h1><%= t('list.header') %></h1>
          <div class="tagline"><%= raw t('list.tagline') %></div>
          <p class="acc_title"><%= t('list.name_title') %></p>
          <p class="acc_content"><%= t('list.name') %></p>
          <p class="acc_title"><%= t('list.acc_title') %></p>
          <p class="acc_content"><%= raw t('list.acc') %></p>
        </div>
        <div class="col-lg-3"></div>
      </div>
    </div>
  </div>
</section>

app/views/home/_our_suggestions.html.erb
<section id="our-suggestions" class="our-suggestions-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <h1><%= t("our_suggestions.header") %></h1>
        <p class="tagline"><%= t("our_suggestions.tagline") %></p>
      </div>
      <div class="col-lg-3"></div>
    </div>
  </div>
</section>

app/views/home/_story.html.erb
<section id="story" class="story-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>A nossa História</h1>
      </div>
    </div>
  </div>
</section>

app/views/home/_suggestions.html.erb
<section id="suggestions" class="suggestions-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <h1><%= t("suggestions.header") %></h1>
        <p class="tagline"><%= t("suggestions.tagline") %></p>
        <%= form_tag("/suggestions", class: "form-horizontal") do %>
          <%= hidden_field_tag :locale, I18n.locale %>
          <div class="form-group">
            <%= text_field_tag "name", nil, class: "form-control",
              placeholder: t("contact.your_name") %>
          </div>
          <div class="form-group">
            <%= text_field_tag "email", nil, class: "form-control",
              placeholder: t("contact.email") %>
          </div>
          <div class="form-group">
            <%= text_area_tag "suggestions", nil, class: "form-control",
              placeholder: t("suggestions.suggestions") %>
          </div>
          <%= submit_tag t("contact.send"), class: "btn btn-default" %>
        <% end %>
      </div>
      <div class="col-lg-3"></div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<!-- Intro Section -->
<%= render partial: 'home/intro' %>

<% if logged_in? %>
  <!-- Info Section -->
  <%= render partial: 'home/info' %>

  <!-- Suggestions Section -->
  <%= render partial: 'home/suggestions' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mariana e Simão" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>
  <!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top" data-offset="120">
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a class="page-scroll" href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#info"><%= t('nav.info') %></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('nav.suggestions') %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <a class="page-scroll" href="#suggestions"><%= t('nav.your_suggestions')%></a>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% opp_locale = ["en", "pt"].reject!{|t| t == I18n.locale.to_s }.first %>
          <%= link_to opp_locale, locale_root_path(locale: opp_locale) %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>